### ISSUE TITLE
Úkol 3

### ISSUE THREAD

**Issue by sverakjan** [MiliWag/du-czechitas-web-2019#1]
Úkol si splnila, mám jen drobné připomínky
1. V CSS máš všechno zbytečně odsazené o 26 mezer
2. Říkali jsme si, že v kódu budeme používat pouze angličtinu, třídy máš česky
3. Jména tříd mají být pouze malými písmeny a slova oddělená pomlčkou

**Comment by MiliWag** [comment]
Děkuji za připomínky. Opravila jsem.
