### ISSUE TITLE
Úkol 4

### ISSUE THREAD

**Issue by ImKubass** [MiliWag/du-czechitas-web-2019#2]
Ahoj,
Pozor na transformaci textu. V HTML by měl být text zapsán standardním způsobem a pokud chceš text kapitálkami, tak použít CSS vlastnosti a to konkretně:
```
	text-transform: uppercase;
```
Řešení spodních tlačítek není ideální. Lepší by bylo tlačítku portfolio nastavit 100% šířku a facebooku a twitteru nastavit 50% šířku.
Pozor na negativní margin, v tomto případně je nevhodný. Dále nastavovat pevnou výšku tlačítku není taky dobrý nápad, lepší je nechat výšku podle obsahu. Ještě nezapomenout na default-ní nastavení tagu ul. Je potřeba resetovat padding.

Jinak v pořádku :)

**Comment by MiliWag** [comment]
Ahoj,

díky za kontrolu, opravila jsem v rámci úkolu k lekci 5.

Pěkný víkend!

Mili
