### ISSUE TITLE
Úkol 5

### ISSUE THREAD

**Issue by AlesRuzickaEu** [MiliWag/du-czechitas-web-2019#3]
Děkuji za úkol.

Když nastavíš flex, tak potom nedává smysl u těch li nechávat display:inline-block, jsou to potomci flexu.

Máš tan nasteveno 

```
.odkazy {
    list-style-type: none;
}
```

což nic nedělá, protože .odkazy není list, selektor by měl být `.odkazy ul`. Stejně tak nebylo třeba dodělávat novou třídku `.flex-container`, ale použí možný existující selektor `.odkazy ul`.

Jinak dobrý. Přehledné CSS, to se mi libí.

Díky

**Comment by AlesRuzickaEu** [comment]
Ještě příště prosí udělej novou složku na nový úkol, jak jsme říkali.

**Comment by MiliWag** [comment]
Ahoj,

díky za kontrolu. Opravu jsem udělala do nové složky. Omlouvám se, že jsem na to minule zapomněla.

Hezký víkend.

Mili
